config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'books#index'
  resources :books do
    member do
      get "like", to: "books#upvote"
      get "dislike", to: "books#downvote"
    end
    resources :comments
  end
  resources :comments do
    member do
      get "like", to: "comments#upvote"
      get "dislike", to: "comments#downvote"
    end
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_attached_file :cover, styles: { medium: "200x250#", thumbnail: "50x50#" }, default_url: "/images/medium/missing.png"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
  validates_presence_of :book_name, :author, :description ,:illustator, :cover, :user_id
  validates_length_of :book_name, :author, :within => 10..74
  validates_length_of :illustator, :within => 3..74, :allow_blank => true
  validates_length_of :description, :minimum => 200, :allow_blank => false
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_votable
  belongs_to :book
  belongs_to :user

  validates_presence_of :content, :user_id, :book_id
  validates_length_of :content, :within => 10..150
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :books
  has_many :comments

  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |user_params|
      user_params.permit(:first_name , :last_name)
    end
    devise_parameter_sanitizer.for(:account_update) do |user_params|
      user_params.permit(:first_name , :last_name)
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!, only: [:index, :show]
  def index
    @books = Book.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)

  end

  def show
  end

  def new
    @book = current_user.books.build
  end

  def edit
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def update

    if @book.update_attributes(book_params)
      redirect_to @book
    else
      render 'edit'
    end
  end

  def destroy
    @book.delete.save

    redirect_to root_path
  end

  def upvote
    @book.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @book.downvote_by current_user
    redirect_to :back
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:book_name, :author, :description ,:illustator, :cover, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @comment = @book.comments.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to book_path(@book)
      flash[:success] = "Created the comment"
    else
      redirect_to book_path(@book)
      flash[:alert] = "Sorry the comment was not save"
    end
  end

  def destroy
    @book = Book.find(params[:book_id])
    @comment = @book.comments.find(params[:id])
    @comment.destroy

    redirect_to book_path(@book)
  end
  def upvote
    @comment = Comment.find(params[:id])
    @comment.upvote_by current_user

    redirect_to :back
  end
  def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_by current_user

    redirect_to :back
  end
  private
  def comment_params
    params.require(:comment).permit(:content, :user_id, :book_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_errors_for(object=nil)
    render('shared/form_errors', object: object) unless object.blank?
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/books/_form.html.erb
  <div class="row col-md-10">
  <%= form_for @book, html: { multipart: true }  do |f| %>

    <%= form_errors_for @book%>

    <div class="form-group col-md-4">
      <%= f.label :book_name%>
      <%= f.text_field :book_name, class: "form-control"%>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :author%>
      <%= f.text_field :author, class: "form-control"%>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :illustator%>
      <%= f.text_field :illustator, class: "form-control"%>
    </div>

    <div class="form-group col-md-8" >
      <%= f.label :description%>
      <%= f.text_area :description, class: "form-control", rows: "16"%>
    </div>

    <div class="form-group col-md-2">
      <%= f.label :cover,  "Attach an Cover Image"  %>
      <%= f.file_field :cover%>

      <% if @book.cover.exists? %>
        <%= image_tag @book.cover.url(:medium), class: "layout-margin" %>
      <% end %>
    </div>

    <div class="clearfix col-md-10">
      <%= f.submit class: "btn btn-success"  %>
    </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<div class="row col-md-offset-2">

<h2>Edit Book</h2>
<%= render 'form' %>
</div>

app/views/books/index.html.erb
<div class="row col-md-offset-3">
  <div class="col-md-9">
    <h1 class="text-center">Lastest Reviews</h1>
    <% @books.each do |book|%>
    <div class="row layout-margin bar bookinfo">
      <div class="col-sm-4 col-md-4">
        <%= image_tag(book.cover.url(:medium))%>
      </div>
      <div class="col-xs-12 col-sm-8 col-md-8 ">
        <div class="layout-margin">
          <div class="col-md-6 col-sm-6 col-xs-6 no-padding-left">
            <p class="text-left clr-blue"><%= book.book_name %></p>
            <p class="text-left clr-gray"> written by <%= book.author%></p>
          </div>
          <div class="col-md-6 col-sm-6 col-xs-6">
            <p class="text-right">Reviewed By <%= book.user.name %></p>
            <p class="text-right clr-gray">on <%=book.created_at.strftime("%b. %d  %Y") %></p>
          </div>
        </div>
        <li><%= book.description.truncate(500) %></li>
        <div class="col-md-6 col-sm-6 col-xs-6 no-padding-left layout-margin">
          <li class="glyphicon glyphicon-comment comment clr-blue"><%= book.comments.count %></li>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6 text-right">
          <li><%= link_to "Continue Reading", book%><i class="glyphicon  glyphicon-menu-right clr-blue"></i></li>
        </div>
        <br>
        <div class="col-md-12 no-padding-left layout-margin">
          <% if book.user == current_user  %>
            <%= link_to "Edit", edit_book_path(book), class: "btn btn-info"%>
            <%= link_to "Delete", book_path(book), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger"%>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>

  </div>
</div>
<div class="text-center">
    <%= will_paginate @books, :renderer => BootstrapPagination::Rails %>
</div>

app/views/books/new.html.erb
<div class="row col-md-offset-2">
<h2>New Book</h2>
<%= render 'form' %>
</div>

app/views/books/show.html.erb
<div class="col-md-offset-2 col-md-8">
  <h2>Show Book</h2>
  <div class="showPage">
    <div class="bar">
      <div class="showimage col-xs-12 no-padding-left">
        <% if @book.cover.present? %>
        <%= image_tag @book.cover.url(:medium)%>
        <% else %>
        <%= image_tag "medium/missing.png"%>
        <% end %>
        <p class="showinfo">Author: <%= @book.author%></p>
        <p class="showinfo">Illustator: <%= @book.illustator%></p>

      </div>
      <div class="showcontent">
        <div>
          <p id="commentcount" class="clr-blue glyphicon glyphicon-comment comment"><%= @book.comments.count %> Comments</p>
          <h5>Reviewed by <%= @book.user.name%></h5>
          <p class="clr-gray"> <%= @book.user.created_at.strftime('%b %d, %Y')%></p>
        </div>
        <p><%= @book.description%></p>

        <ul class="list-inline">
          <%= link_to  like_book_path(@book), class: "btn btn-default", method: :get  do %>
          <%= @book.get_upvotes.size %> Like
          <% end %>
          <%= link_to  dislike_book_path(@book), class: "btn btn-default", method: :get  do %>
          <%= @book.get_downvotes.size %> Dislike
          <% end %>
          <% if @book.user == current_user %>
          <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger"%>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="commentsection ">
    <h3>Join the discussion</h3>
    <p><%=  render "comments/form" %></p>
      <% @book.comments.each do |comment| %>
      <div class="layout-margin bar">
        <div class="list-inline">
          <p><%= comment.user.name %></p>
          <p class="clr-gray"><%= time_ago_in_words(comment.created_at) %> Ago</p>
        </div>
        <p class="clearfix"><%= comment.content %></p>
        <ul class="list-inline">
          <%= link_to like_comment_path(comment),class: "btn btn-default", method: :get  do %>
            <%= comment.get_upvotes.size  %> Like
          <% end %>
          <%= link_to dislike_comment_path(comment),class: "btn btn-default", method: :get  do %>
            <%= comment.get_downvotes.size  %> Dislike
          <% end %>

          <% if comment.user == current_user %>
            <%= link_to 'Delete', [comment.book, comment],
            method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure? '}, class: "btn btn-danger" %>
          <% end %>
        </ul>
      </div>
      <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for ([@book, Comment.new]) do |f| %>
  <%= form_errors_for @book%>
  <div class="form-group">
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<%= render  'shared/header' %>


<%= render  'shared/navbar' %>


<div class="container-fluid">
  <div class="col-md-12">
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
  <!-- <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p> -->
  <%= yield :form_errors %>
  <%= yield %>
  </div>
</div>

</body>
</html>

app/views/shared/_form_errors.html.erb
<% content_for :form_errors do %>
  <% if object.errors.any?  %>
    <p>
      <%= pluralize(object.errors.count, "error") %> prevented the form from being saved:
    </p>

    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_header.html.erb
<header>
  <section class="container over-lay text-center">
      <h1>Book Reviews</h1>
      <div class="space"></div>
      <div class="book_week">
        <div class="week">
          <h2>52 Week 52 Books</h2>
          <h4>For a Serial Procrastinator This Will Be Difficult.</h4>
        </div>
      </div>
      <div class="btn-space"></div>
      <div class="header_btn">
        <li><%= link_to "Book List", books_path , class: " btn btn-link" %></li>
        <p>*subject to change</p>
      </div>
    </div>
  </section>
</header>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

			<%= link_to "Book List", books_path , class: "navbar-brand" %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
						<li><%= link_to "New book", new_book_path%></li>
						<li><%= link_to "Account", edit_user_registration_path%></li>
						<li><%= link_to "Sign Out", destroy_user_session_path,:method => :delete%></li>
				<% else %>
						<li><%= link_to "Sign Up", new_user_registration_path%></li>
						<li><%= link_to "Log In", new_user_session_path%></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>